### ISSUE TITLE
安装就报错，依赖版本不对

### ISSUE THREAD

**Issue by chris-fung** [solidjs-use/solidjs-use#11]
### Describe the bug

![图片](https://user-images.githubusercontent.com/6920145/220185222-0c81fc33-1d47-42cb-aadd-c7a9d4c6f3ad.png)

### Reproduction

pnpm 安装报错

### System Info

```Shell
macos 已有rxjs
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/solidjs-use/solidjs-use/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/solidjs-use/solidjs-use/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://solidjs-use.github.io/solidjs-use/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/solidjs-use/solidjs-use/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a solid-js issue and not a framework-specific issue. it should likely be reported to https://github.com/solidjs/solid instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/solidjs-use/solidjs-use/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dream2023** [comment]
OK，晚上回去看看

**Comment by dream2023** [comment]
经排查，淘宝源缓存问题，可以指定源安装，或者换成官方源

有问题：`npm info @solidjs-use/shared`
无问题：`npm info @solidjs-use/shared --registry=http://registry.npmjs.org`

![WeChatWorkScreenshot_34e5e8c8-8110-42fb-8ab5-27ce6c8f36a2](https://user-images.githubusercontent.com/19297757/220563053-b0eb4e78-4c65-49bc-9bda-54c5f404e622.png)

![WeChatWorkScreenshot_4b2bc249-eb68-42a0-8bda-688ed95790de](https://user-images.githubusercontent.com/19297757/220563074-db7cdd59-cc1a-4212-9106-02a30639d5a5.png)

**Comment by dream2023** [comment]
![image](https://user-images.githubusercontent.com/19297757/220563551-8f9da465-ab28-4f28-8a44-bc99121397d7.png)

**Comment by chris-fung** [comment]
谢谢～问题已解决
